### ISSUE TITLE
More ticks

### ISSUE THREAD

**Issue by PhantomBoat** [vincent0955/Visual-metronome#1]
Great plugin, really easy to use and very useful! It would be even more useful if it had more ticks to choose from beyond 4 as end game weapons and content often are 5 or 7 ticks.

Default colors of course would get less distinct if a greyscale is used. Personally if support for more ticks were added I would do "light blue, dark blue, light green, dark green, light red, dark red, black". I don't have any form of colorblindness so I don't know how it would work for that but I think users will be able to set up colors that work for them as the plugin makes it very easy to change the colors of the ticks.

10 ticks is the most of I know for any cycle but for me 7 ticks is large enough spread as if I need to count to 10 I can count to 5 two times.

**Comment by vincent0955** [comment]
Hey, thank you. This is the second time I've got this suggestion so I guess its a good suggestion. I might as well just add 10 colors and put them in a section of the config, which should hopefully be enough for most if not all purposes. Thanks for the feedback.

**Comment by vincent0955** [comment]
Updated now. Thanks for the suggestion.
