### ISSUE TITLE
Suggestion: Option to increase size of the Tick Number

### ISSUE THREAD

**Issue by robuuuste** [vincent0955/Visual-metronome#13]
Hey, 

Currently, when you increase the size of the box, it doesn't increase the size of the number. It would be nice if we could increase the size of the number aswell.

https://i.imgur.com/genMNcc.gif

**Comment by vincent0955** [comment]
Hey, basically I looked and I don't think that's possible. But if it is, I think it would require a workaround, which idk if I know how to do. If anyone else wants to try, feel free to.

**Comment by vincent0955** [comment]
Nevermind, it is possible. I'm working on implementing fonts and font sizes now and it should have this feature soon.

**Comment by vincent0955** [comment]
Hey, in V1.4 the font size of the number now also scales with the size of the box. The update should be up soon. Thanks for the suggestion.
