### ISSUE TITLE
Show tick number above player showing in interfaces 

### ISSUE THREAD

**Issue by Casesos** [vincent0955/Visual-metronome#15]
![tEqLbDZ](https://user-images.githubusercontent.com/90038205/180583446-17a35a4e-5395-4513-bcd4-fabff81839b6.gif)
The tick number shows while in the bank  ABOVE_SCENE I'd imagine.

**Comment by vincent0955** [comment]
Oops yeah I didn't know there was "BELOW_WIDGETS" so I used "ALWAYS_ON_TOP". I fixed it now, the change should show up soon.

**Comment by Julien-Menard** [comment]
I have the problem, but for the true tile overlay
