### ISSUE TITLE
[Bug] Lowering number of colors can break plugin

### ISSUE THREAD

**Issue by saltedpotatos** [vincent0955/Visual-metronome#2]
If you lower the number of colors and your tickCounter is greater than your colorCycle / number of colors, the plugin will go to the 10th tick color and get stuck until you disable and re-enable the plugin.

Taking a quick peek, I'm guessing you can alter the if check [here](https://github.com/vincent0955/Visual-metronome/blob/ba1d030971380b8b5440f26aa71b663768660ccc/src/main/java/com/visualmetronome/visualmetronomePlugin.java#L94) , but maybe catching the config change and resetting the tickCounter would be a cleaner long term solution

**Comment by vincent0955** [comment]
Thanks for notifying me, I see the problem. I'll check it out, I'll probably just make it reset the TickCounter when the config is changed.

**Comment by vincent0955** [comment]
Fixed in V1.2.3, thanks.
