### ISSUE TITLE
Only two colors

### ISSUE THREAD

**Issue by Puzzle-Drops** [vincent0955/Visual-metronome#22]
![image](https://user-images.githubusercontent.com/86485071/211486588-626bc900-175b-46e1-a412-3a66619cf8cb.png)
This only displays two colors. It will count 1, 2, 3, 4 all in Tick Color. Then again in Tock Color. Then cycle back to Tick Color instead of doing 4 more ticks in 3rd and then again in 4th color.

**Comment by vincent0955** [comment]
yeah this is intentional actually, if you read the description under "tick count" it says that it only supports two colours, because it would be a little cluttering to code that in. So unfortunately you'll have to use only 2 colours if you're using tick counts higher than 2.

**Comment by vincent0955** [comment]
Hey actually I decided to add this anyway since someone else mentioned it a while ago. So your issue should be fixed as soon as the update goes out.
