### ISSUE TITLE
Feature Request: "True Tile Fill Color", but for "Tick Color", "Tock Color", "3rd Tick Color" etc.

### ISSUE THREAD

**Issue by ghost** [vincent0955/Visual-metronome#27]
Title. I'm not a fan of bright/flashy/cluttery visuals, so I'd love to minimize the clutter by making the tiles' borders/outlines 100% transparent and use transparent fill color in tiles instead. Right now that's possible only for **all** of 'tick', 'tock', '3rd' -tiles etc., so as of rn I'm unable to see true tile changing color but fill only.

**Comment by vincent0955** [comment]
Not a bad idea, I'll add it when I can

**Comment by ghost** [comment]
> Not a bad idea, I'll add it when I can

Nice! Thanks.

**Comment by vincent0955** [comment]
I added it in the last update, so it should be there whenever runelite devs decide to pull it. Thanks for the suggestion
