### ISSUE TITLE
Default Box Size setting doesn't apply on client restart

### ISSUE THREAD

**Issue by asherbasher** [vincent0955/Visual-metronome#30]
Whenever I load RuneLite, my "Default Box Size" setting is correctly set to what I want, but the actual visual size of the box is the default of 25. I have to manually change the setting up and down to 'activate' it again.

![2023-07-07 16-48-31](https://github.com/vincent0955/Visual-metronome/assets/10160470/3e0c456d-9caa-4a5b-b364-70f85c797b04)

**Comment by vincent0955** [comment]
Yes you're right. I just fixed it, It should work whenever the update gets pulled

Thanks for pointing that out
