### ISSUE TITLE
Allow moving overhead tick number

### ISSUE THREAD

**Issue by MaxedWhip** [vincent0955/Visual-metronome#35]
"Show tick number above player" overlaps (numbers are on top of eachother) with attack timer metronome plugin, could this be moveable slightly to combat this?

**Comment by vincent0955** [comment]
Yeah it turns out that that plugin uses the same code to render the number so its exactly the same position. I'll add an option to change it once I have the time, thanks for mentioning it

**Comment by vincent0955** [comment]
I finally got to it, added the ability to change the height
