### ISSUE TITLE
Overhead tick counter rendering under Overhead Prayers

### ISSUE THREAD

**Issue by Russ36363** [vincent0955/Visual-metronome#37]
Hi, this seems to have started with today's update (April 17 2024). 

When "Show tick number above player" is checked, the counter is now rendered underneath the overhead prayer, making it difficult to read. Verified via recordings from a few days ago where the tick number was being rendered on top of the overhead prayer.

**Comment by vincent0955** [comment]
Ah I knew it would probably break something. The "Show tick number" should work the same as before after RL devs merge this update. Thanks for letting me know

**Comment by Russ36363** [comment]
confirmed fixed after merged in and updated in RL, thanks!

**Comment by vincent0955** [comment]
Np, let me know if you find any other rendering issues with the tile indicator, if you use it.
