### ISSUE TITLE
Color Per Tick Not Working

### ISSUE THREAD

**Issue by bgibbons0531** [vincent0955/Visual-metronome#39]
Version: `1.4.5.4`

Settings:
![image](https://github.com/user-attachments/assets/ab1809b3-f2c8-4417-a547-40a4356b9005)

Expected Behavior:

Each tick uses its corresponding color
1: white
2: white
3: red
4: blue
5: green

Actual Behavior:
First 5 tick cycle: white
Second 5 tick cycle: white
Third 5 tick cycle: red
Fourth 5 tick cycle: blue
Fifth 5 tick cycle: green.

This was working at some point, but just noticed the issue when trying to use it today at colosseum.

**Comment by bgibbons0531** [comment]
Changing tick count to 1 solves the problem, however I still feel like it's not super intuitive that that is how the behavior works. Feel free to close if you disagree, but maybe worth changing the name of the setting or something?

**Comment by vincent0955** [comment]
Yeah that's intentional and I named it the same way as in the original metronome plugin but it does get a bit confusing with how many settings there are now. The description of the settings should clarify, it shows once hover your mouse over a setting.
