### ISSUE TITLE
[Feature Request] adding numbers

### ISSUE THREAD

**Issue by forshoot** [vincent0955/Visual-metronome#4]
Hi, thanks for making the plugin. I was wondering if it was possible to add numbers in/on top of the box indicating which tick of the cycle you're on (e.g. 1 for tick/white, and 2 for tock/black). I work much better with numbers than with colors, and I'd assume it'd help color blind people who prefer a visual metronome as well.

**Comment by vincent0955** [comment]
Thanks for the suggestion, I think this could be easily implemented since there used to be a title option, so I could probably add numbers. It might be a little small though since it would have to be the regular font size, but I'll try to add it.
