### ISSUE TITLE
[Bug] Increasing tick count breaks tick number

### ISSUE THREAD

**Issue by Bukinnear** [vincent0955/Visual-metronome#8]
Hi! Love this mod!

I've noticed, however, that if you increase the tick count to any number above 1 (eg. 3), the number will count from [0, 1, -1] and then return.

Also, it might be nice if the count started at '1' instead of '0'.

**Comment by vincent0955** [comment]
It's funny that its taken so long for someone to notice that, I guess no one uses the tick count function enough. Should be fixed now in v1.3.6 and the count also starts from 1 now. Thanks for your feedback.

**Comment by Bukinnear** [comment]
It's likely that is been noticed, I'm just the first to complain about it :)
Thanks very much, mate, appreciate it.

**Comment by vincent0955** [comment]
No problem! Yeah it was noticed but no one bothered to report it even though it was probably bugged for quite a while.
