### ISSUE TITLE
[Feature Request] Enable/Disable button

### ISSUE THREAD

**Issue by Bukinnear** [vincent0955/Visual-metronome#9]
Following on from orlp's request for a enable/disable checkbox, having a checkbox in the configuration is actually slower than just disabling the plugin from the plugins list.

Would you consider adding a button on the sidebar, similar to World Switcher, or Grand Exchange? 
I'm not sure if everyone likes having more clutter on their sidebar, but I know that I personally have to search for the plugin regularly to enable/disable it.

**Comment by Bukinnear** [comment]
I've just realized that you can favorite plugins to keep them at the top of the list, so this just became a lot lower priority, but still might be nice if you had the inclination.

Love your work, regardless!

**Comment by vincent0955** [comment]
Yeah, glad you found a solution. I don't think a sidebar section would be feasible since it would add unnecessary clutter for only one function. Thank you!
